export const feedActivities: string[] = [
  // Explore stage: opportunity discovery, expertise analysis, readiness scoring
  "Opportunity assessment completed for SaaS onboarding",
  "Market gap identified in compliance automation",
  "Expertise analysis mapped 12 transferable skills",
  "Venture readiness score calculated: 84/100",
  "Industry demand signals pulled for healthcare ops",
  "Competitive landscape scanned for project management",
  "3 high-fit opportunities surfaced from consulting background",
  "Opportunity assessment completed for fintech advisory",
  "Domain expertise scored across 6 verticals",
  "Market timing analysis run for AI training tools",
  "Opportunity assessment completed for logistics optimization",
  "Transferable skill map generated from product management",
  "Revenue potential modeled for B2B data services",
  "Niche viability scored for remote team tooling",
  "Opportunity assessment completed for e-commerce ops",
  "Demand curve analyzed for supply chain visibility",
  "5 adjacent markets identified from HR background",
  "Competitive density mapped for developer tools",
  "Venture readiness score calculated: 71/100",
  "Expertise overlap found with procurement automation",
  "Opportunity assessment completed for cybersecurity training",
  "Market gap identified in restaurant tech",
  "Skill adjacency mapped for financial modeling",
  "Industry trend signals aggregated for edtech",
  "Opportunity assessment completed for real estate analytics",
  "Buyer willingness validated for operations consulting",
  "7 monetizable skills identified from engineering background",
  "Venture readiness score calculated: 92/100",
  "Market saturation check completed for CRM tools",
  "Opportunity assessment completed for retail workforce",
  "Demand analysis run for legal document automation",
  "Expertise depth scored for marketing analytics",
  "Competitive moat analysis completed for payroll tools",
  "Opportunity assessment completed for construction scheduling",
  "Market entry timing evaluated for climate tech",
  "Transferable skill map generated from operations leadership",
  "4 underserved segments found in recruiting tech",
  "Venture readiness score calculated: 67/100",
  "Opportunity assessment completed for insurance workflows",
  "Domain fit analysis run for content platforms",

  // Build stage: positioning, messaging, pricing, offer design
  "Positioning canvas generated for compliance SaaS",
  "Messaging matrix built with 8 angle variations",
  "Pricing model structured for tiered advisory",
  "ICP definition refined for mid-market CFOs",
  "Offer framework drafted for productized audit service",
  "Value proposition tested across 3 buyer segments",
  "Positioning iteration completed: sharper differentiation angle",
  "Buyer journey mapped for enterprise procurement leads",
  "Messaging hierarchy established for developer tools",
  "Pricing hypothesis updated based on willingness-to-pay data",
  "ICP definition refined for series A founders",
  "Competitive positioning mapped against 4 incumbents",
  "Offer structure finalized for managed compliance service",
  "Brand voice calibrated for technical buyer audience",
  "Messaging matrix built with 6 pain-point angles",
  "Positioning canvas generated for HR analytics platform",
  "Pricing tiers structured: starter, growth, enterprise",
  "ICP definition refined for VP of Engineering personas",
  "Value proposition sharpened for cost-reduction positioning",
  "Buyer objection framework mapped for sales enablement",
  "Positioning iteration completed: repositioned from tool to system",
  "Messaging matrix built with 5 urgency triggers",
  "Pricing model structured for usage-based billing",
  "ICP definition refined for ops managers at scale-ups",
  "Offer framework drafted for fractional CTO service",
  "Positioning canvas generated for supply chain platform",
  "Competitive differentiator identified: speed to deployment",
  "Messaging hierarchy established for non-technical buyers",
  "Pricing hypothesis updated: annual discount added",
  "Buyer persona synthesized from 3 interview transcripts",
  "Positioning iteration completed: authority angle selected",
  "Messaging matrix built with 4 social proof variants",
  "ICP definition refined for director-level marketing leads",
  "Offer structure finalized for subscription advisory",
  "Value proposition tested: ROI framing outperformed",
  "Positioning canvas generated for data pipeline tooling",
  "Pricing model structured for per-seat licensing",
  "Messaging hierarchy established for C-suite audience",
  "Buyer journey mapped for self-serve SaaS conversion",
  "Positioning iteration completed: niche-down to healthcare",

  // Launch stage: assets, outreach, GTM, landing pages, lead magnets
  "Landing page copy generated for beta launch",
  "Lead magnet outline created: 5-day email course",
  "Outreach sequence drafted: 4-touch cold email",
  "Go-to-market playbook assembled for Q2 launch",
  "Launch checklist completed: 18 items verified",
  "Waitlist page drafted with social proof section",
  "Email nurture sequence built: 7 messages",
  "Outbound sequence drafted for LinkedIn outreach",
  "Landing page copy generated for product demo",
  "Lead magnet created: ROI calculator template",
  "Campaign structure mapped for Product Hunt launch",
  "Outreach sequence drafted: warm intro template",
  "Go-to-market timeline built: 6-week sprint",
  "Launch asset generated: one-pager PDF",
  "Waitlist conversion copy optimized",
  "Email welcome sequence drafted: 5 messages",
  "Outbound sequence drafted for cold outreach to VPs",
  "Landing page copy generated for case study",
  "Lead magnet outline created: industry benchmark report",
  "Launch checklist completed: 22 items verified",
  "Campaign structure mapped for email-first launch",
  "Outreach sequence drafted: partnership introduction",
  "Go-to-market playbook assembled for early access",
  "Launch asset generated: comparison chart",
  "Landing page copy generated for free trial",
  "Lead magnet created: assessment scorecard template",
  "Outbound sequence drafted for event follow-up",
  "Email onboarding sequence built: 4 messages",
  "Launch asset generated: feature announcement email",
  "Campaign structure mapped for community-led launch",
  "Outreach sequence drafted: referral ask template",
  "Landing page copy generated for webinar signup",
  "Lead magnet outline created: workflow automation guide",
  "Go-to-market timeline built: 4-week sprint",
  "Launch checklist completed: 15 items verified",
  "Waitlist page drafted with urgency countdown",
  "Outbound sequence drafted for agency outreach",
  "Launch asset generated: social proof carousel",
  "Email re-engagement sequence built: 3 messages",
  "Landing page copy generated for annual plan upsell",

  // Grow stage: experiments, channels, traction, referrals, briefs
  "Growth experiment queued: LinkedIn organic vs paid",
  "Channel test prepared for LinkedIn content strategy",
  "Traction playbook generated for cold email channel",
  "Referral program structure designed: 2-sided incentive",
  "Daily brief generated: 3 actions, 2 insights",
  "14 validation leads identified from outbound campaign",
  "A/B test structured for landing page headline",
  "Channel scoring updated: email outperforming social",
  "Growth experiment queued: SEO content cluster test",
  "Traction playbook generated for community-led growth",
  "Referral loop designed: milestone-based rewards",
  "Daily brief generated: pipeline review + next moves",
  "Channel test prepared for Twitter/X thread strategy",
  "8 warm leads identified from webinar attendees",
  "A/B test structured for pricing page layout",
  "Growth experiment queued: partnership co-marketing",
  "Traction playbook generated for paid acquisition",
  "Distribution strategy mapped for newsletter sponsorships",
  "Daily brief generated: 4 actions, 1 blocker flagged",
  "Channel scoring updated: referrals highest conversion",
  "Growth experiment queued: product-led onboarding flow",
  "11 validation leads identified from content funnel",
  "A/B test structured for email subject lines",
  "Traction playbook generated for affiliate program",
  "Referral program structure designed: tiered rewards",
  "Daily brief generated: weekly metrics summary",
  "Channel test prepared for podcast guest strategy",
  "Growth experiment queued: free tool as lead magnet",
  "Distribution strategy mapped for cross-promotion network",
  "6 warm leads identified from community engagement",
  "A/B test structured for CTA button copy",
  "Channel scoring updated: organic search climbing",
  "Growth experiment queued: webinar funnel optimization",
  "Traction playbook generated for content marketing",
  "Daily brief generated: 2 wins, 1 experiment to close",
  "19 validation leads identified from SEO content",
  "Referral loop designed: reward unlock at 3 invites",
  "Channel test prepared for YouTube educational content",
  "Growth experiment queued: cold email personalization test",
  "Distribution strategy mapped for influencer partnerships",

  // Build & creative: AI build prompts, creative asset prompts, tool exports
  "Build prompt generated for Cursor: SaaS dashboard",
  "Cursor project spec exported with 12 user stories",
  "Claude skill generated: automated client onboarding",
  "Bolt build prompt created: landing page with auth",
  "Midjourney prompt generated: brand hero image",
  "DALL-E prompt set created: 6 ad creative variants",
  "Sora video prompt drafted: 30s product demo",
  "Lovable build prompt exported: waitlist MVP",
  "Brand identity framework generated",
  "Ad creative prompt set generated for social campaign",
  "Replit build prompt created: API integration layer",
  "Video ad script drafted for YouTube pre-roll",
  "Product walkthrough storyboard created for Sora",
  "Claude Code prompt exported: data pipeline automation",
  "Visual asset prompt set created: 8 social media cards",

  // Mixed: varied actions across all stages
  "Offer strategy generated for fractional COO service",
  "Competitive analysis updated with 2 new entrants",
  "Venture concept scored: 88/100 market fit",
  "Positioning canvas generated for AI writing assistant",
  "Landing page copy generated for founder community",
  "Growth experiment queued: retargeting pixel campaign",
  "ICP definition refined for solo founders",
  "Lead magnet outline created: founder toolkit bundle",
  "Channel test prepared for Reddit AMAs",
  "Messaging matrix built with 7 transformation angles",
  "Outreach sequence drafted: investor update template",
  "Daily brief generated: conversion funnel review",
  "Pricing model structured for freemium conversion",
  "Traction playbook generated for viral mechanics",
  "Launch asset generated: animated product walkthrough",
  "Buyer journey mapped for bottom-up enterprise adoption",
  "A/B test structured for onboarding flow variants",
  "Opportunity assessment completed for martech stack",
  "Email nurture sequence built: abandon cart recovery",
  "Competitive positioning mapped against market leader",
  "Growth experiment queued: referral program v2",
  "Venture readiness score calculated: 79/100",
  "Go-to-market playbook assembled for vertical expansion",
  "Offer framework drafted for done-for-you service tier",
  "Channel scoring updated: direct outreach best ROI",
  "Landing page copy generated for industry-specific demo",
  "Positioning iteration completed: outcome-first messaging",
  "Lead magnet created: benchmark comparison tool",
  "Daily brief generated: 5 actions, experiment results in",
  "Distribution strategy mapped for strategic alliance launch",
];
