import type { BlogPost } from "./blog";

export const august2026Posts: BlogPost[] = [
  {
    slug: "vertical-agents-eating-horizontal-saas",
    title:
      "Vertical AI Agents Are Eating Horizontal SaaS, and the Reason Is Pricing",
    category: "Business Design",
    date: "2026-07-30",
    thumbnail: "spiral-draw",
    excerpt:
      "Agents built for one industry are scaling faster than any software cohort before them. The cause is not capability. It is that they sell completed work rather than seats.",
    readTime: "6 min read",
    body: [
      "Vertical AI agents, built for one industry, one workflow, one role, are growing faster than any previous software cohort. The usual explanation is that focused products work better than general ones, which is true and does not explain the speed.",
      "The structural cause is a pricing change. Horizontal software sells seats. A vertical agent sells finished work. When a buyer moves from needing fifty CRM licences to needing five thousand tickets resolved this month, every part of the business model changes with them.",
      "## Why the unit matters more than the product",
      "A seat is a proxy for value. It assumes that more people using the software means more benefit, which held while software made a person faster and stopped holding when software started completing the task.",
      "Completed work is not a proxy. It is the thing the buyer wanted. That collapses the entire argument a vendor normally has to make. Nobody needs to be persuaded that a resolved ticket is worth something, and nobody needs a business case to compare the price of one against what it currently costs them.",
      "## What this does to the sale",
      "It removes the hardest conversation in B2B software, which is establishing that the product produces value at all. A seat-priced tool spends its entire first year arguing about adoption, utilisation, and whether the licences are being used. An outcome-priced agent argues about volume and accuracy, which are both measurable.",
      "It also changes who buys. Seats come out of a software budget with a procurement process attached. Completed work often comes out of an operational budget, where the comparison is to the cost of doing it another way rather than to other software.",
      "## The trap in going pure outcome",
      "The temptation is to price entirely on results, and the current guidance from people running these businesses is not to, at least at first. The recommended structure is hybrid: a small floor plus a usage layer, held until accuracy is proven in production.",
      "The reason is that pure outcome pricing transfers all accuracy risk to the vendor before the vendor knows their own accuracy. A small early customer with messy data can produce a month where the agent resolves very little and the vendor earns almost nothing, for reasons that are the customer's rather than the product's.",
      "A floor covers cost to serve while the accuracy question is still open. Once the numbers are boring and predictable, the floor can shrink.",
      "## What a domain expert should take from this",
      "The opportunity is not to build an agent. Agent capability is available to everyone and improves regardless of what you do. The opportunity is knowing which unit of completed work is worth buying in an industry you already understand.",
      "That is a genuinely hard question and it is not answerable from outside. Is it a resolved ticket, a reviewed contract, a validated claim, a closed defect, a benchmarked lane? The unit has to be something the industry already counts, already argues about, and already assigns a cost to. Choose the wrong unit and the pricing conversation never becomes arithmetic.",
      "Somebody who spent a decade in that industry knows which number gets reported upward every month. That knowledge is the product decision, and it precedes any technical one.",
      "See [why seat-based pricing is shrinking](/blog/seat-based-pricing-is-shrinking) for the wider shift, and [hybrid pricing](/blog/hybrid-pricing-what-most-ai-companies-use) for how the floor and usage layer fit together.",
    ],
    pullquote:
      "The unit has to be something the industry already counts, already argues about, and already assigns a cost to. Choose the wrong one and the pricing conversation never becomes arithmetic.",
    comparison: {
      left: "Selling seats",
      right: "Selling completed work",
      items: [
        {
          left: "Value is a proxy the vendor must argue for",
          right: "Value is the thing the buyer asked for",
        },
        {
          left: "First year spent on adoption and utilisation",
          right: "Conversation is volume and accuracy",
        },
        {
          left: "Comes from a software budget",
          right: "Comes from an operational budget",
        },
        {
          left: "Procurement compares against other tools",
          right: "Procurement compares against doing it another way",
        },
      ],
    },
  },
  {
    slug: "what-narrow-ai-products-prove",
    title: "What the Fastest-Growing AI Companies Prove About Narrow Products",
    category: "From Experience to Business",
    date: "2026-08-01",
    thumbnail: "scatter-converge",
    excerpt:
      "Harvey passed $190 million ARR in legal. Sierra reached $100 million in seven quarters on customer service. Neither built a general product, and solo founders are running the same play at smaller scale.",
    readTime: "6 min read",
    body: [
      "Harvey, built for legal work, reached roughly $190 million in annual recurring revenue and an $11 billion valuation in March 2026, with more than 100,000 lawyers across 60 countries. Sierra, built for customer service, reached $100 million ARR in seven quarters while charging per resolved ticket.",
      "Those are funded companies and their numbers are not a template for anyone reading this. The instructive part is what they chose not to build.",
      "## Neither one is general",
      "Both had the option to be horizontal. The underlying capability does not care whether it reviews a lease or a support ticket, and a general product has a larger addressable market on paper.",
      "They went narrow anyway, because the value is not in the capability. It is in knowing what correct looks like in one domain, and that knowledge does not generalise. What counts as a correctly resolved support ticket has nothing in common with what counts as a correctly reviewed contract, and no amount of model quality bridges that.",
      "## The smaller version of the same play",
      "Solo founders are routinely reaching $300,000 to $500,000 in annual recurring revenue on a single vertical agent, with small teams clearing a million. Those numbers matter more to most people reading this than Harvey's do.",
      "At that scale the economics are unusual. A single-workflow product serving a few hundred customers in one industry needs no sales team, no category creation, and no funding. It needs someone who knows the workflow well enough to define correct.",
      "## Why this favours experience over technical skill",
      "Defining correct is the hard part and it is the part that cannot be researched. It requires having been wrong about it before, having seen the edge case that broke the rule, and knowing which exceptions matter and which are noise.",
      "A technically strong founder entering an unfamiliar industry has to acquire that by observation, slowly, while shipping a product that is wrong in ways they cannot see. Someone who spent nine years in the industry starts with it and has to acquire the technical part instead, which is now the cheaper of the two.",
      "That inversion is recent. For most of the last two decades it ran the other way.",
      "## What narrow actually requires",
      "Not a small market. A specific one. The distinction matters because founders often narrow by shrinking their ambition rather than by sharpening their definition.",
      "Sharpening means being able to state, in one sentence, the unit of work your product completes and the standard it must meet. If you cannot say that sentence yet, more building will not produce it. Talking to people who do the work will.",
      "See [the micro-specialist advantage](/blog/micro-specialist-advantage) for the services version of this, and [how to find a vertical worth building in](/blog/find-a-vertical-in-an-ignored-industry) for choosing the domain.",
    ],
    pullquote:
      "The value is not in the capability. It is in knowing what correct looks like in one domain, and that knowledge does not generalise.",
  },
  {
    slug: "eu-ai-act-article-50-now-live",
    title:
      "The EU AI Act Transparency Rules Are Live. Here Is What Actually Applies.",
    category: "Venture Systems",
    date: "2026-08-04",
    thumbnail: "pulse-radar",
    excerpt:
      "Article 50 took effect on 2 August 2026 and applies immediately to systems already on the market. The obligations are narrower than the commentary suggests, and the penalties are not.",
    readTime: "7 min read",
    body: [
      "Article 50 of the EU AI Act took effect on 2 August 2026. The European Commission published guidelines alongside it and began enforcing the new transparency requirements the same day.",
      "The most important detail for anyone already running a product: the obligations apply immediately to all in-scope systems, regardless of when they were placed on the market. There is no grandfathering. A tool that shipped in 2024 is in scope today.",
      "## The four things that require disclosure",
      "Direct interaction with a person. If your system talks to someone, a chatbot, a voice assistant, an agent, you disclose that they are dealing with AI, unless it would already be obvious to a reasonably informed person.",
      "AI-generated content. Synthetic audio, image, video, or text must be marked as machine-readable and detectable as artificially generated.",
      "Emotion recognition and biometric categorisation. If you use either, the people subjected to it must be informed.",
      "Deep fakes and AI-generated text on matters of public interest. Both carry labelling duties.",
      "## What is not on that list",
      "Most of what a small vertical product does. If your system analyses data and shows a human the result, and no part of it pretends to be a person or generates synthetic media, your Article 50 exposure is narrow.",
      "This is worth stating plainly because the volume of commentary has been high and much of it is written for enterprise compliance functions with a very different risk profile. Reading it, a small founder could reasonably conclude they need a programme they do not need.",
      "## The penalties are real",
      "Non-compliance can reach €15 million or 3% of worldwide annual turnover, whichever is higher. For a company with no turnover to speak of, the fixed figure is the one that matters, and it is not proportionate to company size in any way that helps.",
      "That asymmetry is the argument for spending an afternoon on this rather than deferring it. The work required for a narrow product is genuinely small. The consequence of having skipped it is not.",
      "## The afternoon of work",
      "Write down every place AI appears in your product and what it does. If any of it interacts with a person as though it were a person, add a disclosure. If any of it generates content, label it. Check what your model provider's terms say about how disclosure duties are split between you and them, because providers and deployers can carry distinct obligations for the same feature.",
      "Then keep a record of what the system decided and on what basis. That is useful for customers before it is ever useful for a regulator, and it is the thing that cannot be reconstructed later.",
      "## What comes next",
      "The heavier high-risk obligations remain deferred, to 2 December 2027 and 2 August 2028. SME simplifications were extended and the Digital Omnibus targets a meaningful reduction in administrative burden for smaller companies.",
      "So the direction of travel for a small vendor is still toward less burden rather than more. August was the date that mattered this year, and for most narrow products it was a disclosure sentence rather than a project.",
      "I wrote about [what to expect from this deadline](/blog/eu-ai-act-august-2026-what-applies) before it landed. The scope held up, and [compliance as a wedge](/blog/compliance-as-a-wedge) covers turning obligations like these into a way in rather than a cost.",
    ],
    pullquote:
      "There is no grandfathering. A tool that shipped in 2024 is in scope today, and the fixed penalty figure is not proportionate to company size in any way that helps.",
    steps: [
      {
        label: "Step 1",
        text: "List every place AI appears in the product and what each does",
      },
      {
        label: "Step 2",
        text: "Disclose anywhere the system interacts as though it were a person",
      },
      { label: "Step 3", text: "Label any content the system generates" },
      {
        label: "Step 4",
        text: "Check how your model provider's terms split disclosure duties with you",
      },
      {
        label: "Step 5",
        text: "Log what the system decided and why, for customers first",
      },
    ],
  },
  {
    slug: "selling-completed-work-not-software",
    title: "Selling Completed Work Instead of Software",
    category: "Business Design",
    date: "2026-08-06",
    thumbnail: "grid-light",
    excerpt:
      "Charging per resolved ticket or reviewed document changes what you are selling. It also transfers accuracy risk to you, which is why almost nobody should start there.",
    readTime: "6 min read",
    body: [
      "Intercom charges roughly $0.99 per resolved ticket. Sierra charges per resolution too. The model is clean, the buyer understands it instantly, and it is the direction the market is moving.",
      "It is also the model most likely to hurt a company that adopts it too early, and the reason is worth understanding before copying it.",
      "## What you are actually selling",
      "Software pricing sells access to a capability and leaves the outcome to the buyer. Completed-work pricing sells the outcome and absorbs the risk of not achieving it.",
      "That is a real transfer, not a framing change. If your agent resolves 60% of tickets when the customer expected 85%, you earn 60% of the revenue you modelled while incurring close to 100% of the cost. The customer is not unhappy in that scenario, which is the confusing part. They paid for what they got. You simply built a business on an accuracy number you had not yet earned the right to assume.",
      "## Why the floor exists",
      "The recommended structure from people operating these businesses is a small per-seat or platform floor plus a usage layer, held until accuracy is proven in production.",
      "The floor is not a way of extracting more money. It covers cost to serve during the period when your accuracy is still an estimate. Cost to serve for an agent product is real and mostly variable, which is different from traditional software where the marginal customer costs almost nothing.",
      "Once accuracy is boring, the floor can shrink toward zero and the outcome component can carry more weight. That sequence is much safer than starting at the end of it.",
      "## The measurement problem nobody mentions",
      "Outcome pricing requires both parties to agree on what happened. For a resolved support ticket that is relatively clean, because the resolution is a system event with a timestamp.",
      "For most other units it is considerably murkier. Was the contract reviewed if a human then changed two clauses? Was the claim validated if it was later appealed? Was the lead qualified if it never converted? Each of those has a defensible answer and a defensible counter-argument, and you will be having that argument with your own customer every month.",
      "The practical filter: if the outcome is recorded by a system neither of you controls, outcome pricing is viable. If it requires judgement, price on something else and keep the outcome as the story rather than the invoice.",
      "## What to do instead early on",
      "Price on a band tied to the size of the thing your product acts on, with a usage component. Tell the outcome story in the sales conversation, quantify it in the proposal, and anchor the price against it. But bill on something that cannot be disputed.",
      "You keep the persuasive power of the outcome without betting the company on an accuracy figure you have not yet proven.",
      "See [why outcome pricing usually is not right](/blog/outcome-pricing-sounds-right-usually-is-not) for the longer argument, and [vertical agents eating horizontal SaaS](/blog/vertical-agents-eating-horizontal-saas) for where the pressure is coming from.",
    ],
    pullquote:
      "If the outcome is recorded by a system neither of you controls, outcome pricing is viable. If it requires judgement, keep the outcome as the story rather than the invoice.",
  },
  {
    slug: "ranking-first-and-invisible-in-ai-answers",
    title: "You Can Rank First on Google and Be Invisible in AI Answers",
    category: "For Marketers",
    date: "2026-08-08",
    thumbnail: "node-network",
    excerpt:
      "AI assistants now generate a large share of B2B product discovery, and your position in them is unrelated to your search ranking. Most companies have never checked.",
    readTime: "6 min read",
    body: [
      "ChatGPT, Perplexity, Google AI Overviews, Gemini, and Copilot now account for a substantial share of product-discovery interactions among B2B buyers, by some measures over 40%.",
      "Your visibility in those answers is not a function of your search ranking. You can hold the first organic position for a term and never be named when a buyer asks an assistant the question that term represents. Most companies have never checked whether that is happening to them, because the tooling to check is new.",
      "## Why the two diverge",
      "Ranking is about matching a page to a query. Citation is about a system deciding your content is the most reliable available basis for a claim it is about to make.",
      "Those reward different things. Ranking rewards structure, links, and relevance signals accumulated over time. Citation rewards specificity, verifiable numbers, named sources, and clear declarative answers. A page can be excellent at the first and unremarkable at the second.",
      "## What the tooling now measures",
      "A category of AI visibility trackers appeared over the past year: Profound, Otterly, Peec, SE Ranking's visibility product, Ahrefs Brand Radar, and others. They monitor how often and in what context a brand appears in AI-generated answers, reporting mention rate, citation frequency, share of voice, sentiment, and which of your pages earn the citations.",
      "The genuinely useful features are narrower than the feature lists suggest. Seeing which exact prompts trigger your brand tells you what to write next. Seeing competitors named beside you tells you what the model considers your category. Seeing which page earned a citation tells you which format works.",
      "## The free version of this",
      "You do not need to buy a tool to start. Write down the twenty questions a buyer asks before purchasing something like yours, in the words they would use speaking to an assistant. Ask each one, across two or three assistants, and record whether you appear, how you are described, and whether the description is accurate.",
      "That takes about an hour. Repeat it monthly. For most small companies the manual version surfaces the same three or four actionable findings a subscription would, and the discipline of doing it matters more than the automation.",
      "## The finding that usually comes first",
      "Almost everyone who runs this exercise discovers the same thing initially: they are described inaccurately rather than omitted. The assistant knows the company exists and characterises it as something adjacent to what it is, usually because the clearest public description of the product is old.",
      "That is a much easier problem than invisibility and it is fixed by publishing an unambiguous, current description of what the product does and who it is for. A stale pricing page or an out-of-date llms.txt actively propagates the wrong answer.",
      "See [generative engine optimisation for solo founders](/blog/geo-for-solo-founders) for the practice, and [the citation economy](/blog/citation-economy-statistics-and-quotes) for what actually earns a mention.",
    ],
    pullquote:
      "Almost everyone who runs this exercise finds they are described inaccurately rather than omitted. That is a much easier problem, and it is caused by a stale page.",
    steps: [
      {
        label: "Step 1",
        text: "Write the twenty questions a buyer asks, in their own words",
      },
      {
        label: "Step 2",
        text: "Ask each across two or three assistants and record the answer",
      },
      {
        label: "Step 3",
        text: "Note whether you appear, and whether the description is accurate",
      },
      {
        label: "Step 4",
        text: "Fix the stale page causing any wrong characterisation first",
      },
      {
        label: "Step 5",
        text: "Repeat monthly. An hour beats a subscription.",
      },
    ],
  },
  {
    slug: "agents-embedded-in-enterprise-apps",
    title:
      "Agents Are Being Embedded Into Enterprise Software. That Is Your Opening.",
    category: "For Operators",
    date: "2026-08-10",
    thumbnail: "orbit-rings",
    excerpt:
      "Gartner expects 40% of enterprise applications to embed AI agents by the end of 2026, up from under 5% last year. The gap that creates is operational, not technical.",
    readTime: "6 min read",
    body: [
      "Gartner expects 40% of enterprise applications to embed AI agents by the end of 2026, up from less than 5% in 2025. The agent market itself is projected to move from around $7.8 billion today toward $52 billion by 2030.",
      "Read as a technology forecast that is unremarkable. Read as an operational forecast it describes a very specific mess arriving in a lot of organisations at once, and mess is where an operator's opportunity usually is.",
      "## What embedding actually means on the ground",
      "It means a large number of companies will shortly have agents acting inside systems they did not choose, configured by vendors rather than by them, taking actions that someone internally is accountable for.",
      "Nobody has decided who reviews those actions. Nobody has decided what happens when one is wrong. Nobody has decided how you would notice if the quality drifted over a quarter. These are not model questions. They are operations questions, and they are being deferred because the capability arrived faster than the governance.",
      "## Why this is an operator's problem specifically",
      "An operator's entire job has always been absorbing the gap between how a system is supposed to work and how it actually works. This is that gap, arriving at scale, in a form nobody has a playbook for yet.",
      "The people best positioned to build for it are not the people building agents. They are the people who have spent years being accountable for processes that partially failed, because they already know which failures are tolerable and which are not, and that judgement is the product.",
      "## The shape of the opening",
      "Not another agent. The layer around agents that somebody in an operations function needs and does not have: a queue of actions for review, a record of what was done and why, a signal when quality moves, and a report that satisfies whoever governs the process.",
      "That layer is unglamorous, industry-specific in its rules, and worth paying for the moment an organisation has an incident. The trajectory is reliably the same: enthusiasm, then volume, then an incident, then an urgent search for oversight. Being in the market at the third stage is considerably better than the first.",
      "## Where to look inside your own organisation",
      "If agents have been switched on anywhere near you, ask three questions. Who reviews what the agent did? What happens when it is wrong? How would we know if it got worse?",
      "If the answers are vague, you have found a product, and you have found it in the best possible way, which is by needing it yourself. Everything else about building it is cheap now. That is the part that is not.",
      "See [agent workflow tooling](/blog/agent-workflow-tooling-opportunity) for the category, and [the operator's case for building](/blog/operators-case-for-building-not-optimising) for the wider argument.",
    ],
    pullquote:
      "Who reviews what the agent did? What happens when it is wrong? How would we know if it got worse? If the answers are vague, you have found a product.",
  },
];
